name: Default Config Settings

on:
  workflow_call:
    inputs:
      application-role:
        description: "Override the default application role."
        type: string
        required: false
      aws-region:
        description: "AWS Region to deploy into."
        type: string
        default: "us-west-2"
      ecr-repo:
        description: "The URI to the ECR repo to use"
        type: string
        required: false
      env:
        description: "Target environment for deploying into"
        type: string
        default: "dev"
      deployment-role:
        description: "Override the default deployment role."
        type: string
        required: false
      project:
        description: "Override the default project name."
        type: string
        required: false
    outputs:
      aws-region:
        description: "The region to deploy into."
        value: ${{ inputs.aws-region }}
      short-rev:
        description: "The Git short rev of the sha that triggered the event."
        value: ${{ jobs.config.outputs.short-rev }}
      account-id:
        description: "The account-id cooresponding to the target environment."
        value: ${{ jobs.config.outputs.account-id }}
      ecr-repo:
        description: "The URI to the ECR repo to use"
        value: ${{ jobs.config.outputs.repo }}
      project:
        description: "The project name."
        value: ${{ jobs.config.outputs.project }}
      application-role:
        description: "The role to attach to the application."
        value: ${{ inputs.application-role || jobs.config.outputs.application-role }}
      depoyment-role:
        description: "The role to use when deploying from this repo."
        value: ${{ inputs.deployment-role || jobs.config.outputs.deployment-role }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      deployment-role: ${{ steps.config.outputs.deployment-role }}
      application-role: ${{ steps.config.outputs.application-role }}
      short-rev: ${{ steps.config.outputs.short-rev }}
      ecr-repo: ${{ steps.config.outputs.ecr-repo }}
    steps:
    - id: config
      run: |
        set -ex
        root_account_id='373477481654' # This feels like it should go somewhere else
        case '${{ inputs.env }}' in
        (prod)  account_id='451834275279';;
        (stage) account_id='534743673678';;
        (qa)    account_id='521312932954';;
        (*)     account_id='146283654498';;
        esac
        project='${{ inputs.project || github.event.repository.name }}'
        deploy_role="arn:aws:iam::${account_id}:role/github-${project}"
        app_role="arn:aws:iam::${account_id}:role/${project}"
        repo="${root_account_id}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${project}"
        echo "ecr-repo=${repo}" >> "${GITHUB_OUTPUT}"
        echo "application-role=${app_role}" >> "${GITHUB_OUTPUT}"
        echo "deployment-role=${deploy_role}" >> "${GITHUB_OUTPUT}"
        printf 'short-rev=%.7s\n' '${{ github.sha }}' >> "${GITHUB_OUTPUT}"
