---
name: git-commit-check

on:
  workflow_call:
    secrets:
      token:
        description: Auth token to use, default to github.token
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.token == '' && secrets.token || github.token }}

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^(feat|bug|fix|hotfix|docs|misc)(: |/)"
          error: "First line must begin with one of 'feat', 'bug', 'fix', 'hotfix', 'docs', 'misc'"
          excludeTitle: 'true'
          excludeDescription: 'true'
          checkAllCommitMessages: "true"
          accessToken: ${{ github.token }}

      - name: Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^.{5,74}$'
          error: 'The maximum line length of 74 characters is exceeded.'
          excludeTitle: 'true'
          excludeDescription: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ github.token }}

      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v1
        with:
          flags: mi
          pattern: '^.?(close[sd]?|fix(e[sd])?|resolve[sd]?): \#[0-9]+$'
          error: "Every commit must resolve/close/fix an issue. Open a new issue for commit's unrelated to existing issues."
          excludeTitle: 'true'
          excludeDescription: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ github.token }}

      - name: Conventional Commit Message
        if: ${{ false }}
        run: |
          set -- $(gh api "repos/{owner}/{repo}/pulls/${{ github.event.pull_request.number }}/commits" --jq '.[].sha')
          git fetch --deepen "$#"
          for sha; do
            git show -s --format='%s%n%n%b' "${sha}" > '/tmp/git-commit-message.log'
            if ! pre-commit run --hook-stage commit-msg --commit-msg-filename '/tmp/git-commit-message.log'; then
              echo 'See: <https://www.conventionalcommits.org/en/v1.0.0/>' >&2
              exit 1
            fi
          done
