name: Run a Node.js command

on:
  workflow_call:
    inputs:
      environment:
        description: Target environment
        type: string
        default: dev
      node-version:
        description: Node.js version to use. Default: auto-detected
        type: string
        required: false
      run:
        description: Which checks to run. E.g. `check:ci`
        type: string
        required: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: node
      run: |
        : detect node-version-file
        node_version='null'
        test -f 'package.json' && node_version="$(jq -r .engines.node ./package.json)"
        if test "${node_version}" != 'null'; then
          echo 'version-file=package.json'  >> "${GITHUB_OUTPUT}"
        else
          for version_file in .nvmrc .node-version .tool-versions; do
            if test -f "${version_file}"; then
              echo "version-file=${version_file}" >> "${GITHUB_OUTPUT}"
              break
            fi
          done
        fi

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ steps.node.output.version-file }}

    - env:
        ENVIRONMENT: ${{ inputs.environment }}
      run: npm ci && npm run ${{ inputs.run }}
