---
name: pre-commit

on:
  workflow_call:

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - id: pre-commit-cache
        run: echo "::set-output name=prefix::pre-commit-${{ runner.os }}-$(python --version --version | sha256sum | awk '{print$1}')"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ steps.pre-commit-cache.outputs.prefix }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ steps.pre-commit-cache.outputs.prefix }}-

      - uses: pre-commit/action@v1.0.1
